CREATE TABLE IF NOT EXISTS films (
	id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	name varchar(100) NOT NULL,
	description varchar(200),
	releaseDate date,
	duration integer,
	rate integer 
);
CREATE TABLE IF NOT EXISTS users (
	id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	email varchar(100) NOT NULL,
	login varchar(100) NOT NULL,
	name varchar(100),
	birthday date
);
CREATE TABLE IF NOT EXISTS friends (
	id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	id_host integer REFERENCES users (id),
	id_friend integer REFERENCES users (id)
);
CREATE TABLE IF NOT EXISTS likes (
	id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	id_film integer REFERENCES films (id),
	id_user integer REFERENCES users (id)
);
CREATE TABLE IF NOT EXISTS genres (
	id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	name varchar(40)
);
CREATE TABLE IF NOT EXISTS film_genre (
	id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	id_film integer REFERENCES films (id),
	id_genre integer REFERENCES genres (id)
);
CREATE TABLE IF NOT EXISTS mpa (
	id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	name varchar(40)
);
CREATE TABLE IF NOT EXISTS mpa_and_film (
	id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	id_film integer REFERENCES films (id),
	id_mpa integer REFERENCES mpa (id)
);
